# Generated by Django 2.1.3 on 2018-11-24 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(db_column='stock_id', primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=4, unique=True)),
                ('company_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('stock_data_id', models.AutoField(db_column='stock_data_id', primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=4)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
            options={
                'db_table': 'stock_data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('stock', 'date')},
        ),
    ]
